apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlCenter
  labels:
    app: controlCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlCenter
  template:
    metadata:
      labels:
        app: controlCenter
    spec:
      containers:
        - name: controlCenter
          image: iure07/controlCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5