apiVersion: apps/v1
kind: Deployment
metadata: 
  name: reservation
  labels: 
    app: reservation
spec: 
  selector: 
    matchLabels: 
      app: reservation
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: reservation
    spec: 
      containers: 
        - name: cm-file
          image: iure07/reservation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RESERVATION_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-dev
                  key: RESERVATION_LOG_LEVEL
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          