apiVersion: v1
kind: Pod
metadata:
  labels:
    test: reservation-liveness
  name: reservation-liveness
spec:
  containers:
  - name: reservation-liveness
    image: iure07/reservation:latest
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5